# Generated by Django 4.0.3 on 2022-04-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCloth', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('typeCloth', models.CharField(choices=[('Hats', 'H'), ('Dresses', 'D'), ('Shoes', 'S'), ('Bags', 'B')], max_length=50)),
            ],
        ),
    ]
