# Generated by Django 4.0.3 on 2022-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_clothes_idcloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='idCloth',
            field=models.IntegerField(),
        ),
    ]
