# Generated by Django 4.0.3 on 2022-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clothes_user_alter_clothestype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
