# Generated by Django 4.0.3 on 2022-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_clothes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='idCloth',
            field=models.CharField(choices=[('Hats', 'H'), ('Dresses', 'D'), ('Shoes', 'S'), ('Bags', 'B')], max_length=50),
        ),
    ]
